from odoo import api, fields, models, _

class TraceabilityMatrixLine(models.Model):
	_name = "traceability.matrix.line"

	vehicle_no=fields.Many2one('transport.vehicle.details',string='Vehicle No',track_visibility='onchange', primary_key=True)	
	module_name=fields.Char('Module Name')
	sub_module_name=fields.Char('Sub-Module Name')
	technical_name=fields.Char('Technical Name')
	#custom_module=fields.Selection('Custom Module')
	responsible=fields.Many2one('hr.employee',string ='Responsible')
	current_status=fields.Char('Current Status')
	features_requirements=fields.Char('Features/ Customer Requirements')
	requirements_specification=fields.Char('Requirements Specification')
	fsdname_link =fields.Char('FSD Name & Link')
	tdname_link=fields.Char('TD Name & Link related to FSD')
	requirements_id=fields.Integer('Related Requirements ID')
	#design_components=fields.Selection('[(Modified/Existing)')
	unit_test_case_link=fields.Char('Unit Test Case Link')
	unit_test_results=fields.Char('Unit Test Results')
	#svn_commits=fields.Selection('SVN Commits')
	svn_folder_path=fields.Char('SVN Folder Path')
	svn_commit_date=fields.Date('SVN Commit Date')
	#code_review=fields.Char.Selection('Code Review')
	#automation_status=fields.Selection('Automation Status')
	automation_code_link=fields.Char('Automation Code Link')
	automation_results=fields.Char('Automation Results')
	integration_system_test_cases=fields.Char('Integration/ System Test Cases')
	integration_system_test_results=fields.Char('Integration/ System Test Results')
	user_manuals_link=fields.Char('User Manuals Link')
	democript=fields.Char('Demo Script')
	sales_decks=fields.Char('Sales Decks')
	last_updated_date=fields.Date('Last Updated Date')
	last_updated_by=fields.Many2one('hr.employee', string='Last Updated By')
	last_review_comments=fields.Char('Last Review Comments')
	last_reviewed_by=fields.Many2one('hr.employee', string='Last Reviewed By')
	last_review_date=fields.Date('Last Review Date')